### ISSUE TITLE
Also replace AZs definitions to one z1

### ISSUE THREAD

**Issue by yanwork** [cloudfoundry/cf-deployment#335]
https://github.com/cloudfoundry/cf-deployment/blob/62a56f4c3bac13d438d68cad0aa8bff2a2619c99/operations/scale-to-one-az.yml#L35

**Comment by dsabeti** [comment]
Hey @yanwork. I'm pretty sure you're trying to point out that the adapter instance group doesn't get updated to use a single AZ. I've prioritized a story to fix this. In the future, if you could provide a bit more detail, it would help for me to understand that problem and prioritize a fix.

**Comment by selzoc** [comment]
This was fixed in https://www.pivotaltracker.com/story/show/152661938

**Comment by dsabeti** [comment]
I think this is still an issue. On the `develop` branch currently, the ops-file scales down to one instance, but does not redefine the list of AZs for the adapter. However, there's a PR to fix this:
https://github.com/cloudfoundry/cf-deployment/pull/334
